services:
  hospital-mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: hospital-mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${SA_PASSWORD}
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - /c/Users/Administrator.WIN-BF90TK6OLJV/hospital-patient-management-system/sql:/var/opt/mssql/scripts:ro
      - /c/Users/Administrator.WIN-BF90TK6OLJV/hospital-patient-management-system/data:/var/opt/mssql/imports:ro
      - mssql-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U SA -P \"$SA_PASSWORD\" -Q \"SELECT 1\""]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  mssql-data:
